<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Daniels-MacBook.local" failures="1" tests="14" name="io.techleadacademy.TestTags" time="2.032" errors="0" timestamp="2020-01-12T11:30:58 EST" skipped="1">
  <testcase classname="io.techleadacademy.TestTags" name="subtract2" time="0.008"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="subtract1" time="0.000"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="divide2" time="0.000"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="logInPerformanceTest2" time="2.017"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="add1" time="0.001"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="methodTimeOut" time="0.002"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="logInPerformanceTest1" time="0.002"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="multiply" time="0.000"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="testUserName1" time="0.001"/>
  <system-out>
Testing log in functionality using valid credentials  </system-out>
  <testcase classname="io.techleadacademy.TestTags" name="logInPerformanceTest3" time="0.000">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at io.techleadacademy.TestTags.logInPerformanceTest3(TestTags.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
    </failure>
  </testcase> <!-- logInPerformanceTest3 -->
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="logInPerformanceTest1" time="0.001"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="add2" time="0.000"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="divide1" time="0.000"/>
  <system-out/>
  <testcase classname="io.techleadacademy.TestTags" name="signUpTest">
    <skipped/>
  </testcase> <!-- signUpTest -->
  <system-out/>
</testsuite> <!-- io.techleadacademy.TestTags -->
